### ISSUE TITLE
Trust Protector Election Administration

### ISSUE THREAD

**Issue by riongull** [dashhive/trust-vote-site#2]
### Tasks for Rion
- [x] Review [draft blog post](https://newsroom.dash.org/preview/OwOkLMWwK7rTwVS6_lzcZQ) for accuracy.
- [x] Copy [Hilawe's Google Form](https://docs.google.com/forms/d/1WvdNOTUswi-GYTI9dyJmLvJ0PXPatgCNvGovEPyfOXc/edit?ts=62313adf) and edit to create the [official one](https://docs.google.com/forms/d/1USpb9TErKa6kRsxNVVOZaf4GbtfPr5w6O2iQAgCuhqM/edit)
- [x] Test "Share [results summary](https://docs.google.com/forms/d/1WvdNOTUswi-GYTI9dyJmLvJ0PXPatgCNvGovEPyfOXc/viewanalytics?ts=62313adf) with respondents" option
- [x] Help AJ complete software updates and testing below
- [x] Reply to Mark with updates for TP announcement blog post
- [x] Update https://github.com/dashhive/trust-vote-site/issues/3 with editing notes, etc
- [x] Announce that voting is open
- [x] Work with AJ to complete https://github.com/dashhive/trust-vote-site/issues/3
- [x] Make Incubator task for Duncan for https://github.com/dashhive/trust-vote-site/pull/6/files
- [x] ~~Possibly add written voting steps for major methods, like [suggested in Discord](https://discord.com/channels/484546513507188745/672789594588184606/961667833853517824) for DMT~~
